project:
  type: website
  
  output-dir: docs
website:
  title: "mysite"
  navbar:
    title: Motina Kashanian # this is the website title as it appears in the top left corner -- clicking on this will jump you back to your landing page from where ever you are
    right: # align navbar items to the right/left/center
      - href: index.qmd
        text: home # use 'text' option to update the name as you want it to appear in your navbar
      - about.qmd
      - resources.qmd
      - href: CV.pdf
        text: cv
      - icon: github # add icons that link to social media, etc.
        href: https://github.com/motinaaa
      - icon: twitter
        href: https://twitter.com/motiinaa
        
        
  page-footer: 
    background: light
    left: 
      - "Copyright 2023, Motina Kashanian"


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true