project:
  type: website
  output-dir: docs

website:
  title: "mysite"
  navbar:
    title: Motina Kashanian
    right:
      - href: Motinaaa.github.io.qmd
        text: Home
      - about.qmd
      - blog.qmd
      - href: CV.pdf
        text: CV
      - icon: github
        href: https://github.com/motinaaa

  page-footer:
    background: light
    left:
      - "Copyright 2023, Motina Kashanian"

format:
  html:
    theme:
      - mystyles.scss
    css: 
      - motina.css
    toc: true
